#!/bin/bash

set -xe

PROJ_ROOT=$PWD

SUFFIX=_rpi

SOURCES_ROOT=$PROJ_ROOT/..

source common.sh

cd $BUILD_ROOT
cmake -DCMAKE_INSTALL_PREFIX=$DEST_ROOT \
      -DTHIRD_PARTY_PATH=$THIRD_PARTY_PATH \
      -DCMAKE_SYSTEM_NAME=RPi \
      -DRPI_TOOLCHAIN=$RPI_TOOLCHAIN \
      -DWITH_C_API=ON \
      -DWITH_TESTING=OFF \
      -DWITH_GPU=OFF \
      -DWITH_PYTHON=OFF \
      -DWITH_SWIG_PY=OFF \
      -DWITH_STYLE_CHECK=OFF \
      -DCMAKE_BUILD_TYPE=Release \
      $SOURCES_ROOT
