#!/bin/bash

set -xe

PROJ_ROOT=$PWD
SUFFIX=

SOURCES_ROOT=$PROJ_ROOT/..

source common.sh

cd $BUILD_ROOT
cmake -DCMAKE_INSTALL_PREFIX=$DEST_ROOT \
      -DTHIRD_PARTY_PATH=$THIRD_PARTY_PATH \
      -DCMAKE_BUILD_TYPE=RelWithDebInfo \
      -DCMAKE_C_FLAGS_RELWITHDEBINFO='-O3' \
      -DCMAKE_CXX_FLAGS_RELWITHDEBINFO='-O3' \
      -DCUDNN_ROOT=${CUDNN_ROOT} \
      -DMKL_ROOT=${MKL_ROOT} \
      -DWITH_STYLE_CHECK=OFF \
      -DWITH_GOLANG=OFF \
      -DWITH_GPU=ON \
      -DWITH_PYTHON=ON \
      -DWITH_SWIG_PY=ON \
      -DCMAKE_PREFIX_PATH="$JUMBO_ROOT" \
      $SOURCES_ROOT

cd $PROJ_ROOT

