set -xe

export CCACHE_DIR=/workspace/.ccache
export CACHE_DIR=/workspace/.cache

mkdir -p ./build && cd ./build

cmake .. -DPY_VERSION=3.7 -DWITH_GPU=ON -DWITH_TESTING=ON -DCMAKE_BUILD_TYPE=Release -DWITH_CUSTOM_DEVICE=ON -DWITH_MKL=ON -DWITH_MKLDNN=ON -DCMAKE_EXPORT_COMPILE_COMMANDS=ON # -DWITH_UNITY_BUILD=ON
# cmake .. -DCMAKE_BUILD_TYPE=Release -DWITH_GPU=OFF -DWITH_TENSORRT=ON -DWITH_ROCM=OFF -DWITH_CINN=OFF -DWITH_DISTRIBUTE=ON -DWITH_MKL=OFF -DWITH_AVX=OFF -DNOAVX_CORE_FILE= -DCUDA_ARCH_NAME=Volta -DNEW_RELEASE_PYPI=OFF -DNEW_RELEASE_ALL=OFF -DNEW_RELEASE_JIT=OFF -DWITH_PYTHON=ON -DWITH_TESTING=ON -DWITH_COVERAGE=OFF -DWITH_INCREMENTAL_COVERAGE=OFF -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DWITH_CONTRIB=ON -DWITH_INFERENCE_API_TEST=ON -DWITH_INFRT=OFF -DPY_VERSION=3.7 -DWITH_PSCORE=ON -DWITH_PSLIB=OFF -DWITH_GLOO=ON -DWITH_XPU=OFF -DWITH_MLU=OFF -DWITH_IPU=OFF -DWITH_CNCL=OFF -DXPU_SDK_ROOT= -DWITH_LITE=OFF -DWITH_XPU_BKCL=OFF -DWITH_ARM=OFF -DWITH_ASCEND=OFF -DWITH_ASCEND_CL=OFF -DWITH_ASCEND_INT64=OFF -DWITH_STRIP=ON -DON_INFER=OFF -DWITH_HETERPS=OFF -DWITH_FLUID_ONLY=OFF -DCUDA_ARCH_BIN= -DWITH_RECORD_BUILDTIME=OFF -DWITH_UNITY_BUILD=ON -DWITH_ONNXRUNTIME=OFF
make -j 32
pip uninstall paddlepaddle-gpu -y
pip install ./python/dist/paddlepaddle_gpu-0.0.0-cp37-cp37m-linux_x86_64.whl
# pip uninstall paddlepaddle -y
# pip install ./python/dist/paddlepaddle-0.0.0-cp37-cp37m-linux_x86_64.whl


# GLOG_v=4 python run.py
# GLOG_vmodule=operator=4 ctest -R test_matrix_rank_op -VV > log.matrix_rank 2>&1


# PR-CI-Py3 cmake
# cmake .. -DCMAKE_BUILD_TYPE=Release -DPYTHON_EXECUTABLE:FILEPATH=/opt/_internal/cpython-3.7.0/bin/python3.7 -DPYTHON_INCLUDE_DIR:PATH=/opt/_internal/cpython-3.7.0/include/python3.7m -DPYTHON_LIBRARIES:FILEPATH=/opt/_internal/cpython-3.7.0/lib/libpython3.so -DWITH_GPU=OFF -DWITH_TENSORRT=ON -DWITH_ROCM=OFF -DWITH_CINN=OFF -DWITH_DISTRIBUTE=ON -DWITH_MKL=OFF -DWITH_AVX=OFF -DNOAVX_CORE_FILE= -DCUDA_ARCH_NAME=Volta -DNEW_RELEASE_PYPI=OFF -DNEW_RELEASE_ALL=OFF -DNEW_RELEASE_JIT=OFF -DWITH_PYTHON=ON -DCUDNN_ROOT=/usr/ -DWITH_TESTING=ON -DWITH_COVERAGE=OFF -DWITH_INCREMENTAL_COVERAGE=OFF -DCMAKE_MODULE_PATH=/opt/rocm/hip/cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DWITH_CONTRIB=ON -DWITH_INFERENCE_API_TEST=ON -DWITH_INFRT=OFF -DINFERENCE_DEMO_INSTALL_DIR=/root/.cache/inference_demo -DPY_VERSION=3.7 -DCMAKE_INSTALL_PREFIX=/paddle/build -DWITH_PSCORE=ON -DWITH_PSLIB=OFF -DWITH_GLOO=ON -DLITE_GIT_TAG=release/v2.10 -DWITH_XPU=OFF -DWITH_MLU=OFF -DWITH_IPU=OFF -DWITH_CNCL=OFF -DXPU_SDK_ROOT= -DWITH_LITE=OFF -DWITH_XPU_BKCL=OFF -DWITH_ARM=OFF -DWITH_ASCEND=OFF -DWITH_ASCEND_CL=OFF -DWITH_ASCEND_INT64=OFF -DWITH_STRIP=ON -DON_INFER=OFF -DWITH_HETERPS=OFF -DWITH_FLUID_ONLY=OFF -DCUDA_ARCH_BIN= -DWITH_RECORD_BUILDTIME=OFF -DWITH_UNITY_BUILD=ON -DWITH_ONNXRUNTIME=OFF
